In [3]:
import math
import numpy as np 

def l2(y_true, y_pred):
    return math.sqrt(np.sum(np.mean(np.square(y_true - y_pred), axis=0))/9)

In [162]:
# a = np.array([[[[1, 2, 3], [4, 13, 16]],[[7, 18, 19], [10, 15, 12]]], [[[2, 4, 6], [5, 17, 19]],[[18, 10, 12], [11, 13, 15]]]])
# b = np.array([[[[4], [5], [6]],[[0],[1],[2]],[[9],[8],[7]]], [[[4], [5], [6]],[[0],[1],[2]],[[9],[8],[7]]]])
a = np.array([[[[1., 2.], [4., 13.]],[[7., 18.], [10., 15.]]], [[[2., 4.], [5., 17.]],[[18., 10.], [11., 13.]]]])

a

array([[[[ 1.,  2.],
         [ 4., 13.]],

        [[ 7., 18.],
         [10., 15.]]],


       [[[ 2.,  4.],
         [ 5., 17.]],

        [[18., 10.],
         [11., 13.]]]])

In [168]:
a = np.array([[[[1., 2.], [4., 13.]],[[7., 18.], [10., 15.]]], [[[2., 4.], [5., 17.]],[[18., 10.], [11., 13.]]]])

def normalization(matrix):
    for i in range(len(matrix)):
        for j in range(matrix.shape[-1]):
            cur_time = matrix[i][:, :, j]
            mean_val = cur_time.mean()
            mx = cur_time.max()
            mn = cur_time.min()
            matrix[i][:, :, j] = np.divide((cur_time-mean_val), (mx-mn))
    return matrix

normalization(a)

array([[[[-0.5       , -0.625     ],
         [-0.16666667,  0.0625    ]],

        [[ 0.16666667,  0.375     ],
         [ 0.5       ,  0.1875    ]]],


       [[[-0.4375    , -0.53846154],
         [-0.25      ,  0.46153846]],

        [[ 0.5625    , -0.07692308],
         [ 0.125     ,  0.15384615]]]])

In [167]:
def guiyi(array):
    mean = array.mean()
    mx = array.max()
    mn = array.min()
    return (array-mean)/(mx-mn)

array = np.array([4,17,10,13])
guiyi(array)

array([-0.53846154,  0.46153846, -0.07692308,  0.15384615])

In [163]:
3.5/9

0.3888888888888889